language: python
python: "3.6"

install:
  - pip install riotwatcher

script:
  - OUT_LOG=$(ci/scripts/test_python_module.sh)
  - if [[ "$OUT_LOG" == "*traceback error*" ]]; then echo "traceback error detected" ; fi